#Parte 2
texto = input("Ingrese un texto...")
letras = input("Ingrese CINCO LETRAS...")
letras = list(letras)
texto = texto.replace("a",letras[0])
texto = texto.replace("e",letras[1])
texto = texto.replace("i",letras[2])
texto = texto.replace("o",letras[3])
texto = texto.replace("u",letras[4])
texto = texto.split(" ")
print(texto)